/**
 * PKCE (Proof Key for Code Exchange) utilities — RFC 7636.
 *
 * Uses the bare global `crypto` object (available as `globalThis.crypto` in
 * browsers, Node 19+, and the vitest node environment) rather than
 * `window.crypto` so that both browser and non-browser environments can call
 * these functions without mocking.
 */

/**
 * Generates a cryptographically random PKCE `code_verifier`.
 *
 * The verifier is 32 random bytes encoded as base64url (43 characters),
 * satisfying RFC 7636 §4.1 (43–128 characters from the unreserved character
 * set `[A-Z a-z 0-9 - . _ ~]`).
 */
export function generateCodeVerifier(): string {
  const array = new Uint8Array(32);
  crypto.getRandomValues(array);
  return base64urlEncode(array);
}

/**
 * Computes the PKCE `code_challenge` from a `code_verifier`.
 *
 * `code_challenge = BASE64URL(SHA-256(ASCII(code_verifier)))` — RFC 7636 §4.2.
 *
 * @param verifier  A `code_verifier` generated by {@link generateCodeVerifier}.
 */
export async function generateCodeChallenge(verifier: string): Promise<string> {
  const data = new TextEncoder().encode(verifier);
  const hash = await crypto.subtle.digest('SHA-256', data);
  return base64urlEncode(new Uint8Array(hash));
}

// ---------------------------------------------------------------------------
// Private helpers
// ---------------------------------------------------------------------------

/** Encodes a `Uint8Array` as a base64url string (no padding). */
function base64urlEncode(bytes: Uint8Array): string {
  // Convert bytes to a binary string, then btoa, then convert to base64url.
  let binary = '';
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(bytes[i]!);
  }
  return btoa(binary)
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '');
}
