/** A configuration object for the UrlHelper class. */
export type UrlHelperConfig = {
  /** The URL of the server that performs the token exchange */
  serverUrlString: string;
  /** FusionAuth client ID */
  clientId: string;
  /** The URI that the user is directed to after the login/register/logout action */
  redirectUri: string;
  scope?: string;

  mePath?: string;
  loginPath?: string;
  registerPath?: string;
  logoutPath?: string;
  tokenRefreshPath?: string;
};

/** The query params associated with URLs generated by the UrlHelper class. */
export type UrlHelperQueryParams = {
  client_id: string;
  redirect_uri?: string;
  post_logout_redirect_uri?: string;
  state?: string;
  scope?: string;
};
