name: Publish @fusionauth/angular-sdk

on: workflow_dispatch

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, 24.x, 26.x]
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Angular SDK - Install packages
        run: yarn install --frozen-lockfile
      - name: Copy Core to Angular
        working-directory: ./packages/sdk-angular
        run: yarn get-sdk-core
      - name: Angular SDK - Test
        run: yarn test:sdk-angular

  publish-sdk-angular:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: setup node for publishing
        uses: actions/setup-node@v4
        with:
          node-version: '26'
          registry-url: 'https://registry.npmjs.org' # This generates the necessary .npmrc

      - name: Angular SDK - Install packages
        run: yarn install --frozen-lockfile

      - name: Angular SDK - Build
        run: yarn build:sdk-angular

      - name: Angular SDK - Publish
        working-directory: ./packages/sdk-angular/dist/fusionauth-angular-sdk
        run: |
          npm install -g npm@latest
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: 'sigstore' # npm uses OIDC when this is any non-empty string
